require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  UseCache: false
  UseServer: false
  NewCops: enable
  SuggestExtensions:
    rubocop-rake: false
  TargetRubyVersion: 3.4
  Exclude:
    - bin/**/*
    - config/**/*
    - db/migrate/*
    - db/schema.rb
    - node_modules/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/users/sessions_controller.rb'

Naming/PredicateName:
  Exclude:
    - 'app/services/turnstile_verifier.rb'
