---
engine_version: 0.4.7
file_version: 2023-04-03 05:50:48.235103000 Z
resources:
- name: chapter
  preferences:
    columns:
    - column_type: richtext
      name: description
    - access_type: read_only
      name: slug
  updated_at: 2023-04-03 05:50:48.235103000 +00:00
- name: feature_flag
  preferences:
    columns:
    - column_type: richtext
      name: description
  updated_at: 2023-03-09 16:16:17.698355000 +00:00
configs:
- key: header.links
  value:
  - name: "⭐ Star on GitHub"
    path: https://github.com/motor-admin/motor-admin-rails
  updated_at: 2023-03-30 00:41:34.130118000 +00:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description:
  updated_at: 2023-03-30 00:41:34.133532000 +00:00
